/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 OrangeBottle.glb 
Author: karmadefender (https://sketchfab.com/karmadefender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/orange-juice-bottle-1837c24636634148935c922e49892daa
Title: Orange Juice Bottle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/OrangeBottle.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.053, 0]}>
        <group rotation={[0, Math.PI / 2, 0]} scale={[1, 0.98, 1]}>
          <group position={[0, -0.397, -0.023]}>
            <mesh geomety={nodes.ManiPiece_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0, 32.61, 0]} scale={[7.517, 3.007, 7.517]} />
            <mesh geometry={nodes.pCube2_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0, 32.672, 7.332]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube3_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0.384, 32.672, 7.322]} rotation={[0, 0.052, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube4_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0.766, 32.672, 7.292]} rotation={[0, 0.105, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube5_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[1.147, 32.672, 7.242]} rotation={[0, 0.157, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube6_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[1.524, 32.672, 7.172]} rotation={[0, 0.209, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube7_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[1.898, 32.672, 7.082]} rotation={[0, 0.262, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube8_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[2.266, 32.672, 6.973]} rotation={[0, Math.PI / 10, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube9_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[2.628, 32.672, 6.845]} rotation={[0, 0.367, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube10_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[2.982, 32.672, 6.698]} rotation={[0, 0.419, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube11_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[3.329, 32.672, 6.533]} rotation={[0, 0.471, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube12_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[3.666, 32.672, 6.35]} rotation={[0, Math.PI / 6, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube13_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[3.993, 32.672, 6.149]} rotation={[0, 0.576, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube14_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[4.31, 32.672, 5.932]} rotation={[0, Math.PI / 5, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube15_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[4.614, 32.672, 5.698]} rotation={[0, 0.681, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube16_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[4.906, 32.672, 5.449]} rotation={[0, 0.733, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube17_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.184, 32.672, 5.184]} rotation={[0, Math.PI / 4, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube18_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.449, 32.672, 4.906]} rotation={[0, 0.838, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube19_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.698, 32.672, 4.614]} rotation={[0, 0.89, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube20_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.932, 32.672, 4.31]} rotation={[0, 0.942, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube21_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.149, 32.672, 3.993]} rotation={[0, 0.995, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube22_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.35, 32.672, 3.666]} rotation={[0, Math.PI / 3, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube23_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.533, 32.672, 3.329]} rotation={[0, 1.1, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube24_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.698, 32.672, 2.982]} rotation={[0, 1.152, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube25_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.845, 32.672, 2.628]} rotation={[0, 1.204, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube26_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.973, 32.672, 2.266]} rotation={[0, 1.257, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube27_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.082, 32.672, 1.898]} rotation={[0, 1.309, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube28_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.172, 32.672, 1.524]} rotation={[0, 1.361, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube29_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.242, 32.672, 1.147]} rotation={[0, 1.414, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube30_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.292, 32.672, 0.766]} rotation={[0, 1.466, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube31_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.322, 32.672, 0.384]} rotation={[0, 1.518, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube32_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.332, 32.672, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube33_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.322, 32.672, -0.384]} rotation={[-Math.PI, 1.518, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube34_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.292, 32.672, -0.766]} rotation={[-Math.PI, 1.466, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube35_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.242, 32.672, -1.147]} rotation={[-Math.PI, 1.414, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube36_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.172, 32.672, -1.524]} rotation={[-Math.PI, 1.361, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube37_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[7.082, 32.672, -1.898]} rotation={[-Math.PI, 1.309, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube38_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.973, 32.672, -2.266]} rotation={[-Math.PI, 1.257, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube39_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.845, 32.672, -2.628]} rotation={[-Math.PI, 1.204, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube40_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.698, 32.672, -2.982]} rotation={[-Math.PI, 1.152, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube41_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.533, 32.672, -3.329]} rotation={[-Math.PI, 1.1, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube42_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.35, 32.672, -3.666]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube43_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[6.149, 32.672, -3.993]} rotation={[-Math.PI, 0.995, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube44_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.932, 32.672, -4.31]} rotation={[-Math.PI, 0.942, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube45_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.698, 32.672, -4.614]} rotation={[-Math.PI, 0.89, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube46_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.449, 32.672, -4.906]} rotation={[-Math.PI, 0.838, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube47_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[5.184, 32.672, -5.184]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube48_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[4.906, 32.672, -5.449]} rotation={[-Math.PI, 0.733, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube49_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[4.614, 32.672, -5.698]} rotation={[-Math.PI, 0.681, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube50_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[4.31, 32.672, -5.932]} rotation={[-Math.PI, Math.PI / 5, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube51_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[3.993, 32.672, -6.149]} rotation={[-Math.PI, 0.576, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube52_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[3.666, 32.672, -6.35]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube53_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[3.329, 32.672, -6.533]} rotation={[-Math.PI, 0.471, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube54_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[2.982, 32.672, -6.698]} rotation={[-Math.PI, 0.419, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube55_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[2.628, 32.672, -6.845]} rotation={[-Math.PI, 0.367, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube56_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[2.266, 32.672, -6.973]} rotation={[-Math.PI, Math.PI / 10, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube57_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[1.898, 32.672, -7.082]} rotation={[-Math.PI, 0.262, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube58_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[1.524, 32.672, -7.172]} rotation={[-Math.PI, 0.209, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube59_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[1.147, 32.672, -7.242]} rotation={[-Math.PI, 0.157, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube60_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0.766, 32.672, -7.292]} rotation={[-Math.PI, 0.105, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube61_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0.384, 32.672, -7.322]} rotation={[-Math.PI, 0.052, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube62_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[0, 32.672, -7.332]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube63_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-0.384, 32.672, -7.322]} rotation={[-Math.PI, -0.052, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube64_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-0.766, 32.672, -7.292]} rotation={[-Math.PI, -0.105, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube65_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-1.147, 32.672, -7.242]} rotation={[-Math.PI, -0.157, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube66_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-1.524, 32.672, -7.172]} rotation={[-Math.PI, -0.209, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube67_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-1.898, 32.672, -7.082]} rotation={[-Math.PI, -0.262, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube68_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-2.266, 32.672, -6.973]} rotation={[-Math.PI, -Math.PI / 10, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube69_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-2.628, 32.672, -6.845]} rotation={[-Math.PI, -0.367, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube70_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-2.982, 32.672, -6.698]} rotation={[-Math.PI, -0.419, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube71_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-3.329, 32.672, -6.533]} rotation={[-Math.PI, -0.471, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube72_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-3.666, 32.672, -6.35]} rotation={[-Math.PI, -Math.PI / 6, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube73_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-3.993, 32.672, -6.149]} rotation={[-Math.PI, -0.576, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube74_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-4.31, 32.672, -5.932]} rotation={[-Math.PI, -Math.PI / 5, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube75_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-4.614, 32.672, -5.698]} rotation={[-Math.PI, -0.681, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube76_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-4.906, 32.672, -5.449]} rotation={[-Math.PI, -0.733, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube77_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.184, 32.672, -5.184]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube78_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.449, 32.672, -4.906]} rotation={[-Math.PI, -0.838, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube79_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.698, 32.672, -4.614]} rotation={[-Math.PI, -0.89, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube80_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.932, 32.672, -4.31]} rotation={[-Math.PI, -0.942, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube81_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.149, 32.672, -3.993]} rotation={[-Math.PI, -0.995, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube82_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.35, 32.672, -3.666]} rotation={[-Math.PI, -Math.PI / 3, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube83_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.533, 32.672, -3.329]} rotation={[-Math.PI, -1.1, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube84_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.698, 32.672, -2.982]} rotation={[-Math.PI, -1.152, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube85_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.845, 32.672, -2.628]} rotation={[-Math.PI, -1.204, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube86_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.973, 32.672, -2.266]} rotation={[-Math.PI, -1.257, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube87_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.082, 32.672, -1.898]} rotation={[-Math.PI, -1.309, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube88_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.172, 32.672, -1.524]} rotation={[-Math.PI, -1.361, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube89_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.242, 32.672, -1.147]} rotation={[-Math.PI, -1.414, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube90_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.292, 32.672, -0.766]} rotation={[-Math.PI, -1.466, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube91_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.322, 32.672, -0.384]} rotation={[-Math.PI, -1.518, -Math.PI]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube92_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.332, 32.672, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube93_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.322, 32.672, 0.384]} rotation={[0, -1.518, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube94_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.292, 32.672, 0.766]} rotation={[0, -1.466, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube95_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.242, 32.672, 1.147]} rotation={[0, -1.414, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube96_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.172, 32.672, 1.524]} rotation={[0, -1.361, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube97_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-7.082, 32.672, 1.898]} rotation={[0, -1.309, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube98_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.973, 32.672, 2.266]} rotation={[0, -1.257, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube99_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.845, 32.672, 2.628]} rotation={[0, -1.204, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube100_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.698, 32.672, 2.982]} rotation={[0, -1.152, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube101_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.533, 32.672, 3.329]} rotation={[0, -1.1, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube102_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.35, 32.672, 3.666]} rotation={[0, -Math.PI / 3, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube103_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-6.149, 32.672, 3.993]} rotation={[0, -0.995, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube104_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.932, 32.672, 4.31]} rotation={[0, -0.942, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube105_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.698, 32.672, 4.614]} rotation={[0, -0.89, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube106_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.449, 32.672, 4.906]} rotation={[0, -0.838, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube107_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-5.184, 32.672, 5.184]} rotation={[0, -Math.PI / 4, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube108_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-4.906, 32.672, 5.449]} rotation={[0, -0.733, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube109_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-4.614, 32.672, 5.698]} rotation={[0, -0.681, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube110_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-4.31, 32.672, 5.932]} rotation={[0, -Math.PI / 5, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube111_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-3.993, 32.672, 6.149]} rotation={[0, -0.576, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube112_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-3.666, 32.672, 6.35]} rotation={[0, -Math.PI / 6, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube113_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-3.329, 32.672, 6.533]} rotation={[0, -0.471, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube114_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-2.982, 32.672, 6.698]} rotation={[0, -0.419, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube115_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-2.628, 32.672, 6.845]} rotation={[0, -0.367, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube116_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-2.266, 32.672, 6.973]} rotation={[0, -Math.PI / 10, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube117_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-1.898, 32.672, 7.082]} rotation={[0, -0.262, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube118_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-1.524, 32.672, 7.172]} rotation={[0, -0.209, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube119_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-1.147, 32.672, 7.242]} rotation={[0, -0.157, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube120_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-0.766, 32.672, 7.292]} rotation={[0, -0.105, 0]} scale={[0.171, 4.497, 0.106]} />
            <mesh geometry={nodes.pCube121_Bottle2CapArnold_0.geometry} material={materials.Bottle2CapArnold} position={[-0.384, 32.672, 7.322]} rotation={[0, -0.052, 0]} scale={[0.171, 4.497, 0.106]} />
          </group>
          <mesh geometry={nodes.Bottle_BottlePlastic_0.geometry} material={materials.BottlePlastic} />
          <mesh geometry={nodes.Juice_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} position={[0, 0.006, 0]} scale={[0.937, 1.009, 0.937]} />
          <mesh geometry={nodes.LabelFront_Bottle2LabelArnold_0.geometry} material={materials.Bottle2LabelArnold} position={[-0.001, 0, 0]} />
          <mesh geometry={nodes.LabelBack_Bottle2LabelArnold_0.geometry} material={materials.Bottle2LabelArnold} position={[0.001, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/OrangeBottle.glb')
