/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/model/WawaOffice.glb 
*/

import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { useRef } from 'react';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger)

export function Model(props) {
  const { nodes, materials } = useGLTF('/src/assets/model/WawaOffice.glb')

  const groupRef = useRef();

  const hero = document.getElementById('hero');

  useGSAP(() => {
    gsap.to(groupRef.current.rotation, {
      y: Math.PI * 2,
      scrollTrigger: {
        trigger: hero,
        start: '0% 0%',
        end: '2000% 0%',
        scrub: true,
      }
    });

  }, []);
 

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
      {/* <mesh geometry={nodes['02_library'].geometry} material={materials['02']} position={[0, 2.114, -2.23]} />
      <mesh geometry={nodes['03_attic'].geometry} material={materials['03']} position={[-1.97, 4.227, -2.199]} /> */}
    </group>
  )
}

useGLTF.preload('/src/assets/model/WawaOffice.glb')
